using System;
using System.Collections.Generic;
using TMPro;
using UnityEngine;

/// <summary>
/// Rotate the junction tiles until current flows from the cell to the antenna.
///
/// The board is generated by carving a real path first and laying the correct pieces along
/// it, then scrambling every rotation. That guarantees a solution exists without needing a
/// solver, and because live tiles light up as soon as they connect to the cell the player
/// always has partial feedback to reason from rather than hunting blind.
/// </summary>
public class CircuitRoutingPuzzle : MonoBehaviour, IPuzzle
{
    public event Action Solved;

    // Connection directions as bit flags: up, right, down, left.
    const int Up = 1, Right = 2, Down = 4, Left = 8;

    class Tile
    {
        public int x, y;
        public int mask;              // current connections, after rotation
        public int solutionMask;      // connections when correctly oriented
        public PuzzleButton button;
        public TMP_Text glyph;
        public bool live;
        public bool locked;           // revealed by a hint, no longer rotatable
    }

    Tile[,] grid;
    int width, height;
    PuzzleStyle style;
    TMP_Text status;
    bool finished;

    public void Build(RectTransform host, PuzzleRequest request, PuzzleStyle s)
    {
        style = s;
        var rng = new System.Random(request.seed);

        width = request.tier == 0 ? 3 : request.tier == 1 ? 4 : 5;
        height = request.tier == 0 ? 3 : request.tier == 1 ? 4 : 4;

        grid = new Tile[width, height];
        for (int x = 0; x < width; x++)
            for (int y = 0; y < height; y++)
                grid[x, y] = new Tile { x = x, y = y };

        CarveSolutionPath(rng);
        FillRemainder(rng);
        Scramble(rng);

        // Layout: a square cell grid, sized so bigger boards still fit the panel.
        float cell = request.tier == 2 ? 68f : 78f;
        float gap = 6f;
        float totalW = width * cell + (width - 1) * gap;
        float totalH = height * cell + (height - 1) * gap;
        float originX = -totalW * 0.5f + cell * 0.5f;
        float originY = totalH * 0.5f - cell * 0.5f + 6f;

        PuzzleWidgets.Label("From", host, s, "CELL →", 15f, s.warm,
            new Vector2(originX - cell * 0.5f - 52f, originY), new Vector2(90f, 22f),
            TextAlignmentOptions.Right);
        PuzzleWidgets.Label("To", host, s, "→ ANTENNA", 15f, s.warm,
            new Vector2(originX + totalW - cell * 0.5f + 62f, originY - (height - 1) * (cell + gap)),
            new Vector2(110f, 22f), TextAlignmentOptions.Left);

        for (int y = 0; y < height; y++)
        {
            for (int x = 0; x < width; x++)
            {
                var t = grid[x, y];
                Vector2 centre = new Vector2(originX + x * (cell + gap), originY - y * (cell + gap));
                var tile = t;
                t.button = PuzzleWidgets.Button("T" + x + "_" + y, host, s, "", centre,
                    new Vector2(cell, cell), () => Rotate(tile), 30f);
                t.glyph = t.button.Label;
                t.glyph.fontSize = cell * 0.5f;
            }
        }

        status = PuzzleWidgets.Label("Status", host, s, "", 17f, s.dim,
            new Vector2(0f, -totalH * 0.5f - 24f), new Vector2(560f, 24f));

        Refresh();
    }

    // ---------------------------------------------------------------- generation

    // Walks a self-avoiding path from the top-left cell to the bottom-right antenna,
    // recording which sides each visited tile must connect on.
    void CarveSolutionPath(System.Random rng)
    {
        var start = new Vector2Int(0, 0);
        var goal = new Vector2Int(width - 1, height - 1);

        var path = new List<Vector2Int> { start };
        var visited = new HashSet<Vector2Int> { start };
        var cursor = start;
        int guard = 0;

        while (cursor != goal && guard++ < 2000)
        {
            // Bias towards the goal so the path stays a sensible length, but allow detours
            // so it is not a straight line every time.
            var options = new List<Vector2Int>();
            void Consider(Vector2Int step)
            {
                var n = cursor + step;
                if (n.x < 0 || n.y < 0 || n.x >= width || n.y >= height) return;
                if (visited.Contains(n)) return;
                options.Add(n);
            }
            Consider(new Vector2Int(1, 0));
            Consider(new Vector2Int(0, 1));
            Consider(new Vector2Int(-1, 0));
            Consider(new Vector2Int(0, -1));

            if (options.Count == 0)
            {
                // Dead end: step back and try again. The tile we abandon has to leave the
                // visited set too, or the retry has nowhere left to go and the walk starves.
                if (path.Count <= 1) break;
                visited.Remove(cursor);
                path.RemoveAt(path.Count - 1);
                cursor = path[path.Count - 1];
                continue;
            }

            // Weight moves that reduce distance to the goal.
            Vector2Int pick = options[0];
            int best = int.MaxValue;
            foreach (var o in options)
            {
                int d = Mathf.Abs(o.x - goal.x) + Mathf.Abs(o.y - goal.y);
                int jitter = rng.Next(0, 3);
                if (d + jitter < best) { best = d + jitter; pick = o; }
            }

            visited.Add(pick);
            path.Add(pick);
            cursor = pick;
        }

        // The random walk can still strand itself against the board edges. A puzzle that
        // cannot be solved would lock a radio part away for good, so fall back to a
        // staircase route, which always connects and is still randomised in where it turns.
        if (path.Count == 0 || path[path.Count - 1] != goal)
            path = StaircasePath(rng, start, goal);

        // Record the required connections along the path.
        for (int i = 0; i < path.Count; i++)
        {
            var cellPos = path[i];
            var t = grid[cellPos.x, cellPos.y];
            if (i > 0) t.solutionMask |= DirectionBetween(cellPos, path[i - 1]);
            if (i < path.Count - 1) t.solutionMask |= DirectionBetween(cellPos, path[i + 1]);
        }

        // The endpoints need a stub facing off-board so they read as terminals.
        grid[0, 0].solutionMask |= Left;
        grid[width - 1, height - 1].solutionMask |= Right;
    }

    // A monotone right/down route from start to goal, with the turns placed randomly.
    // It can never fail or self-intersect, which is what makes it a safe fallback.
    static List<Vector2Int> StaircasePath(System.Random rng, Vector2Int start, Vector2Int goal)
    {
        var path = new List<Vector2Int> { start };
        var cursor = start;
        while (cursor != goal)
        {
            bool canRight = cursor.x < goal.x;
            bool canDown = cursor.y < goal.y;
            bool goRight = canRight && (!canDown || rng.Next(0, 2) == 0);
            cursor = goRight ? new Vector2Int(cursor.x + 1, cursor.y)
                             : new Vector2Int(cursor.x, cursor.y + 1);
            path.Add(cursor);
        }
        return path;
    }

    static int DirectionBetween(Vector2Int from, Vector2Int to)
    {
        if (to.y < from.y) return Up;
        if (to.y > from.y) return Down;
        if (to.x > from.x) return Right;
        return Left;
    }

    // Tiles not on the path get a plausible piece so the board does not advertise the route.
    void FillRemainder(System.Random rng)
    {
        int[] shapes = { Up | Down, Left | Right, Up | Right, Right | Down, Down | Left, Left | Up };
        for (int x = 0; x < width; x++)
            for (int y = 0; y < height; y++)
            {
                var t = grid[x, y];
                if (t.solutionMask != 0) continue;
                t.solutionMask = shapes[rng.Next(shapes.Length)];
            }
    }

    void Scramble(System.Random rng)
    {
        for (int x = 0; x < width; x++)
            for (int y = 0; y < height; y++)
            {
                var t = grid[x, y];
                t.mask = t.solutionMask;
                int turns = rng.Next(0, 4);
                // A straight piece looks identical after two turns, so make sure at least one
                // tile of the path is genuinely wrong rather than trivially pre-solved.
                for (int i = 0; i < turns; i++) t.mask = RotateMask(t.mask);
            }

        // Guard against an accidentally already-solved board.
        if (IsSolved())
        {
            var t = grid[0, 0];
            t.mask = RotateMask(t.mask);
            if (IsSolved()) t.mask = RotateMask(t.mask);
        }
    }

    static int RotateMask(int mask)
    {
        // Clockwise: up->right, right->down, down->left, left->up.
        int result = 0;
        if ((mask & Up) != 0) result |= Right;
        if ((mask & Right) != 0) result |= Down;
        if ((mask & Down) != 0) result |= Left;
        if ((mask & Left) != 0) result |= Up;
        return result;
    }

    // ---------------------------------------------------------------- play

    void Rotate(Tile t)
    {
        if (finished || t.locked) return;
        t.mask = RotateMask(t.mask);
        Refresh();
    }

    // Flood-fills from the cell, following only mutually agreeing connections.
    void RecomputeLive()
    {
        for (int x = 0; x < width; x++)
            for (int y = 0; y < height; y++)
                grid[x, y].live = false;

        // The cell feeds the top-left tile only if that tile still has its outward stub.
        var source = grid[0, 0];
        if ((source.mask & Left) == 0) return;

        var queue = new Queue<Tile>();
        source.live = true;
        queue.Enqueue(source);

        while (queue.Count > 0)
        {
            var t = queue.Dequeue();
            TryFlow(t, Up, 0, -1, Down, queue);
            TryFlow(t, Right, 1, 0, Left, queue);
            TryFlow(t, Down, 0, 1, Up, queue);
            TryFlow(t, Left, -1, 0, Right, queue);
        }
    }

    void TryFlow(Tile from, int outward, int dx, int dy, int inward, Queue<Tile> queue)
    {
        if ((from.mask & outward) == 0) return;
        int nx = from.x + dx, ny = from.y + dy;
        if (nx < 0 || ny < 0 || nx >= width || ny >= height) return;
        var n = grid[nx, ny];
        if (n.live) return;
        if ((n.mask & inward) == 0) return;      // the neighbour must face back
        n.live = true;
        queue.Enqueue(n);
    }

    bool IsSolved()
    {
        RecomputeLive();
        var sink = grid[width - 1, height - 1];
        return sink.live && (sink.mask & Right) != 0;
    }

    void Refresh()
    {
        bool solved = IsSolved();
        int liveCount = 0;

        for (int x = 0; x < width; x++)
            for (int y = 0; y < height; y++)
            {
                var t = grid[x, y];
                if (t.live) liveCount++;
                if (t.glyph) t.glyph.text = Glyph(t.mask);
                if (t.glyph) t.glyph.color = t.live ? style.warm : style.dim;
                if (t.button)
                    t.button.SetResting(t.locked
                        ? new Color(1f, 1f, 1f, 0.12f)
                        : t.live ? new Color(1f, 0.72f, 0.36f, 0.16f) : style.inkSlot);
            }

        if (status)
        {
            status.text = solved ? "CIRCUIT COMPLETE" : liveCount + " junction" + (liveCount == 1 ? "" : "s") + " energised";
            status.color = solved ? style.good : style.dim;
        }

        if (solved && !finished)
        {
            finished = true;
            Solved?.Invoke();
        }
    }

    // Box-drawing glyphs, so each piece's connections are unmistakable at a glance.
    static string Glyph(int mask)
    {
        switch (mask)
        {
            case Up | Down: return "│";
            case Left | Right: return "─";
            case Up | Right: return "└";
            case Right | Down: return "┌";
            case Down | Left: return "┐";
            case Left | Up: return "┘";
            case Up | Right | Down: return "├";
            case Right | Down | Left: return "┬";
            case Down | Left | Up: return "┤";
            case Left | Up | Right: return "┴";
            case Up | Right | Down | Left: return "┼";
            case Up: return "╵";
            case Right: return "╶";
            case Down: return "╷";
            case Left: return "╴";
            default: return "·";
        }
    }

    public bool RevealHint()
    {
        // Snap one misaligned path tile to its solved rotation and lock it.
        for (int x = 0; x < width; x++)
            for (int y = 0; y < height; y++)
            {
                var t = grid[x, y];
                if (t.locked || t.mask == t.solutionMask) continue;
                t.mask = t.solutionMask;
                t.locked = true;
                Refresh();
                return true;
            }
        return false;
    }

    public void Dispose() { }
}
